# models.py
# ------------------------------------------------------------
# This module defines all dataclasses used across the CareRoute
# application. These serve as structured containers for:
#   - vitals entered by the user
#   - combined symptom + vitals inputs
#   - triage decisions produced by the AI/safety layer
#   - facility info returned by Google Maps
#   - facility recommendations (facility + distance)
#   - history records saved locally
# ------------------------------------------------------------

from dataclasses import dataclass        # For creating lightweight, immutable data structures
from typing import List, Optional        # Optional types & list typing for attributes
from datetime import datetime            # Used for timestamps in history records


# ------------------------------------------------------------
# User Vitals
# ------------------------------------------------------------
@dataclass
class Vitals:
    """
    Optional vital signs provided by the user.
    These values may influence triage severity or trigger red flags.

    Fields:
        temperature_c (float or None): Temperature in Celsius.
        pain_score (int or None): 0–10 pain scale.
        pregnant (bool or None): Pregnancy status.
        trauma (bool or None): Whether recent trauma occurred.
    """
    temperature_c: Optional[float] = None
    pain_score: Optional[int] = None
    pregnant: Optional[bool] = None
    trauma: Optional[bool] = None


# ------------------------------------------------------------
# Combined input sent to the triage model
# ------------------------------------------------------------
@dataclass
class SymptomInput:
    """
    Full user input passed to the triage engine.

    Fields:
        text (str): Raw symptom description from the user.
        vitals (Vitals): Optional vital signs (temperature, pain, etc.).
    """
    text: str
    vitals: Vitals


# ------------------------------------------------------------
# Output of AI + rule-based triage
# ------------------------------------------------------------
@dataclass
class TriageDecision:
    """
    The final triage result returned by the AI and validated
    by the rule-based safety layer.

    Fields:
        urgency_level (str):
            One of: "HOME", "CLINIC", "URGENT", "ER".
            Determines how serious the condition likely is.

        score (int):
            Numeric 1–4 representation of urgency:
                1 → mild (home)
                4 → severe (ER)
            This is helpful for UI color scales.

        explanation (str):
            Natural language explanation generated by the model
            explaining the triage reasoning.

        red_flags (List[str]):
            List of red-flag symptoms detected.
            Used to override AI decision if needed.
    """
    urgency_level: str
    score: int
    explanation: str
    red_flags: List[str]


# ------------------------------------------------------------
# Facility returned from Google Places (raw info)
# ------------------------------------------------------------
@dataclass
class Facility:
    """
    Core information about a healthcare facility.
    This corresponds to individual Places API results.

    Fields:
        name (str): Facility name.
        type (str): Mapped from urgency (e.g., "CLINIC", "ER").
        lat (float): Latitude of the facility.
        lon (float): Longitude of the facility.
        address (str): Short or full formatted address.
        phone (str): Phone number (usually blank for Nearby Search).
    """
    name: str
    type: str
    lat: float
    lon: float
    address: str
    phone: str


# ------------------------------------------------------------
# Facility recommendation + distance + URL
# ------------------------------------------------------------
@dataclass
class FacilityRecommendation:
    """
    A complete recommendation displayed to the user.

    Fields:
        facility (Facility): The full facility data.
        distance_km (float): Distance from the user in kilometers.
        maps_url (str): Deep link to Google Maps for navigation.
    """
    facility: Facility
    distance_km: float
    maps_url: str


# ------------------------------------------------------------
# A single stored triage session (for My Data page)
# ------------------------------------------------------------
@dataclass
class HistoryRecord:
    """
    One entry in the user's triage history.

    Fields:
        timestamp (datetime):
            UTC timestamp when the triage was completed.

        symptoms_text (str):
            The original symptoms text typed by the user.

        urgency_level (str):
            Triage result for that session.

        facility_names (List[str]):
            Only the names of recommended facilities at that time.
            (We don't store full facility info to keep history lightweight.)
    """
    timestamp: datetime
    symptoms_text: str
    urgency_level: str
    facility_names: List[str]
